### ISSUE TITLE
Add One-Step Matching Loss in Matching Surrogate Objective

### ISSUE THREAD

**Issue by ChandlerBang** [Guang000/Awesome-Dataset-Distillation#6]
Hey Guang, Bo and Tongzhou, 

Thank you for maintaining this great repository!

The paper [Condensing Graphs via One-Step Gradient Matching](https://arxiv.org/pdf/2206.07746.pdf) proposes to use a surrogate loss, namely one-step gradient matching loss, to guide the learning process. While it focuses on graph data, it could also be categorized into the `Matching Surrogate Objective` category. Would you mind adding this paper into `Matching Surrogate Objective`?

Thanks for the consideration.

**Comment by Guang000** [comment]
Hey Wei, thanks for your kind reminder. The current criteria for this project are that each paper appears in only one section. I think "GNN" might be the more important category for your excellent paper. Sometimes a paper is indeed included in more than one category. For example, my medical paper also involves privacy protection. We will follow up to discuss a reasonable solution. Thanks again for your interest! Let us know if you have any questions.

**Comment by ChandlerBang** [comment]
Thank you for the efforts in organizing the papers. I agree that one paper for multiple categorizes can be more precise but also challenging. Hope we can eventually find a solution.

**Comment by SsnL** [comment]
Hi Wei,

Thanks for reaching out. I concur with Guang that each paper should be placed in one category, as a general guideline.

Please correct me if my following understanding is wrong. For your paper, while it uses gradient matching, the changes from DC is a bit minor (i.e., sampling from init distn rather than the trajectories) and there is no evidence that this is an improvement on the common DD benchmarks, which admittedly is very vision-focused, but is still the most established benchmark for general-purpose DD methods. Therefore, in my opinion, the paper is best categorization as a paper focusing on distilling graph datasets.

Please let me know what you think!

Best,
Tongzhou

**Comment by ChandlerBang** [comment]
Hi Tongzhou, 

Thank you for the explanation. Your understanding is correct and I agree that this paper shall be categorized into the GNN section when only one category is allowed. I also encountered similar issues since I am also maintaining several Github paper lists. I understand that including one single paper in multiple categories may make the repo super heavy and add some extra burden to the maintainers, as we can foresee that there will be a rapid rise in the number of dataset distillation papers. 

The current layout for this repo is great and thanks again for your efforts in maintaining it.

Best,
Wei

**Comment by SsnL** [comment]
Thanks for your understanding! I'm closing this issue now. Feel free to re-open if you have further questions or concerns.
