### ISSUE TITLE
Is there any open source code for this paper in medical?

### ISSUE THREAD

**Issue by Liareee** [Guang000/Awesome-Dataset-Distillation#8]
Hey Guang, Bo and Tongzhou,

Thank you for maintaining this great repository!

The paper in application of medical [Soft-Label Anonymous Gastric X-ray Image Distillation](https://arxiv.org/abs/2104.02857) (Guang Li et al., ICIP 2020)] has been marked a "code" icon. 
However when I click on the icon, the page does not jump correctly, and it also jumps to the current repository.
Does this paper have open source code? I didn't find any relevant content on github. If you can provide relevant ideas, I would be very grateful!

Thanks for the consideration.

**Comment by Guang000** [comment]
Hey Erica, 

First of all, thank you for your interest in my paper, because the research involves a private dataset from the University of Tokyo and hence we have not made the code publicly available, but our research is based on the soft-label dataset distillation and implemented according to its repo, which you can check it at [here](https://github.com/ilia10000/dataset-distillation). I apologize for the code tag because this paper collection project begins with this paper, so I added the code tag, which has been fixed.

Best,
Guang

**Comment by Liareee** [comment]
Hey Guang, 

Thank you for your prompt reply and your efforts to organize the paper.
I'll look into the link you shared, thanks again!

Best,
Erica
